[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    powerbroker2/ELMduino@^3.4

build_flags =
    -DUSER_SETUP_LOADED=1
    -include src/Setup_ESP32_2432S028R_ST7789.h
